version: 2

models:
  - name: dim_state
    columns:
      - name: state_name
        data_tests:
          - unique
          - not_null

  - name: dim_county
    columns:
      - name: county_name
        data_tests:
          - unique
          - not_null
      - name: state_abbreviation
        data_tests:
          - unique
          - not_null          
